language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
cache:
  directories:
    - "node_modules"
before_install:
  - sudo apt-get install redis-server
  - sudo service redis-server start
  - npm i -g npm@latest
  - npm i -g typescript
install:
  - npm ci
script:
  - npm run build:publish
after_success: npm run coverage
