
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
cache:
  directories:
    - "node_modules"
before_install:
  - sudo apt-get install redis-server
  - npm i -g npm@latest
install:
  - npm ci
script:
  - npm test
after_success: npm run coverage